services:
    kavita:
        image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
        container_name: kavita
        volumes:
            - /media/Manga:/manga            # Manga is just an example you can have the name you want. See the following
            - /media/Comics:/comics          # Use as many as you want
            - /media/Books:/books            #
            - /srv/kavita/config:/kavita/config     # Change './data if you want to have the config files in a different place.
                                        # /kavita/config must not be changed
        environment:
            - TZ=UTC
        ports:
            - "5000:5000" # Change the public port (the first 5000) if you have conflicts with other services
        restart: unless-stopped
