services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.0.2 # 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4000M
    volumes:
      - mealie-data:/app/data/
    env_file:
      - mealie.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mealie-net
        
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - mealie-pgdata:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - postgres.env
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - mealie-net

volumes:
  mealie-data:
  mealie-pgdata:

networks:
  mealie-net:
    driver: bridge
