version: '3'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 3000:8080
#    network: host
    environment:
      - 'OLLAMA_BASE_URL=http://0.0.0.0:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped

volumes:
  open-webui: 
    external: true
