name: Tdarr-Node
services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1002
      - UMASK_SET=002
      - nodeName=PCNode
      - serverIP=192.168.8.179
      - serverPort=8266
      - serverUrl=192.168.8.179:8266
      - inContainer=true
      - ffmpegVersion=7
      - nodeType=mapped
      - priority=-1
      - cronPluginUpdate=
      - apiKey=
      - maxLogSizeMB=10
      - pollInterval=2000
      - startPaused=false
      - transcodecpuWorkers=2
      - healthcheckcpuWorkers=2
#      - transcodegpuWorkers=4    needs gpu passthrough, not doing on main PC

    volumes:
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
      - /media:/media
      - /transcode_cache:/temp

