services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe/London
       ports:
            - 5055:5055
       volumes:
            - /srv/jellyseerr/config:/app/config
       restart: unless-stopped
       network_mode: "host"
